# This file was generated by GoReleaser. DO NOT EDIT.
class Katafygio < Formula
  desc "Discover and continuously backup Kubernetes objets as yaml files in git"
  homepage "https://github.com/bpineau/katafygio"
  version "0.8.3"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bpineau/katafygio/releases/download/v0.8.3/katafygio_0.8.3_darwin_amd64.tar.gz"
    sha256 "f0c3ff01fba96d9ac8e3906d98b33990a6acc4adff71027e1f11d25f43eba162"
  end

  def install
    bin.install "katafygio"
  end

  test do
    system "#{bin}/katafygio version"
  end
end
